plugins{
    id 'java-test-fixtures'
}

bootJar {
    enabled = false
    archiveFileName = 'gidosa-common.jar'
}

jar {
    enabled = true
}

test {
    enabled = false
}
//tasks.bootJar { enabled = false }
//tasks.jar { enabled = false }

dependencies {
//    implementation 'com.fasterxml.jackson.core:jackson-core'
    implementation "com.fasterxml.jackson.core:jackson-databind"

    // Jsoup Java HTML Parser
    implementation 'org.jsoup:jsoup:1.19.1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // testFixture
    testFixturesImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.register("prepareKotlinBuildScriptModel") {}