# 서버포트
server:
  port: 9095
#  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: true   # 스프링 기본 에러 페이지 비활성화
    include-exception: true
    include-stacktrace: always
    path: /error       # 에러 발생시 이동할 경로

# spring-web-jpa
spring:
  application:
    name: gidosa-full-webadmin

  datasource:
    mysql:
      master1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        #        jdbc-url: jdbc:mysql://35.216.107.29:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
        jdbc-url: jdbc:mysql://localhost:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: password
        max-pool-size: 20

  thymeleaf:          # 타임리프
    cache: true
#    prefix: classpath:/templates/
#    suffix: .html
#    view-names: thymeleaf/*
#    enabled: true
  #    check-template-location: true

#  mvc:
##    static-path-pattern: /**
#    view:         # 제이에스피
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
#    context-path: /api

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update        # ddl-auto와 같음
        show_sql: true      # java코드로 짠 sql을
        format_sql: true    # sql문 pretty하게 보여줌
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        temp:
        #          use_jdbc_metadata_defaults: false
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        enable_lazy_load_no_trans: false  # open-in-view 비슷?
        #        default_schema: users
        #        transaction:
        #          jta:   # Java Tomcat Application? or Java Transaction API?
        #            platform: true
        query:
          fail_on_pagination_over_collection_fetch: true
    #        default_batch_fetch_size: 500

  mail:
    host: ${SMTP_MAIL_GIDOSA_HOST}
    port: ${SMTP_MAIL_GIDOSA_PORT}
    username: ${SMTP_MAIL_GIDOSA_USERNAME}
    password: ${SMTP_MAIL_GIDOSA_PASSWORD}
    sender-display: 위험안전 지도사
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secret: vosdfay6ghfasdfasldfjasldfmxcfvojalksnfskdsdgfn

## mybatis
#mybatis:
#  #  mapper-locations: classpath:mappers/**/*.xml
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: net.gidosa.full.webadmin.mappers
##  configuration:
##    map-underscore-to-camel-case: true

# log

file:
  upload:
#    path: ~/apps-gidosa/attachment-files
    # path: /home/gapture/apps-gidosa/attachment-files/webadmin
    path: /home/gapture/apps-gidosa/attachment-files