spring:
  profiles:
    active: local
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common
        -

#file:
#  upload:
#    path: /path/to/upload/directory




