# 서버포트
server:
  port: 9097
#  forward-headers-strategy: framework
#  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
  error:
    whitelabel:
      enabled: false   # 스프링 기본 에러 페이지 비활성화
    include-exception: true
    include-stacktrace: always
    path: /error       # 에러 발생시 이동할 경로

spring:
  application:
    name: gidosa-full-webapp

#  web:
#    resources:
#      static-locations:
#        - classpath:/static/
#      add-mappings: false

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    add-properties: false

  datasource:
    mysql:
      master1:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://35.216.107.29:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
        jdbc-url: jdbc:mysql://dev-inner-bastion.jobio.kr:1306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
#        jdbc-url: jdbc:mysql://localhost:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: password
        max-pool-size: 20
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  ##    url: jdbc:mysql://35.216.107.29:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
  #    url: jdbc:mysql://localhost:3306/safety_gidosa?useSSL=false&serverTimezone=Asia/Seoul
  #    username: root
  #    password: password
  #    hikari:
  #      maximum-pool-size: 20

  thymeleaf:          # 타임리프
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    view-names: thymeleaf/*
#    enabled: true
#    check-template-location: true

  mvc:
    throw-exception-if-no-handler-found: true
##    static-path-pattern: /**
##    static-path-pattern: /static/**
#    view:         # 제이에스피
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
#    context-path: /api
    session:
      timeout: 30m  # 세션 타임아웃 설정
      cookie:
        http-only: true
        secure: false  # HTTPS 사용 시 true로 설정

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update        # ddl-auto와 같음
        show_sql: true      # java코드로 짠 sql을
        format_sql: true    # sql문 pretty하게 보여줌
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        temp:
        #          use_jdbc_metadata_defaults: false
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        enable_lazy_load_no_trans: false  # open-in-view 비슷?
        #        default_schema: users
        #        transaction:
        #          jta:   # Java Tomcat Application? or Java Transaction API?
        #            platform: true
        query:
          fail_on_pagination_over_collection_fetch: true
    #        default_batch_fetch_size: 500

  mail:
    host:
    port:
    username:
    password:
    sender-display: 위험안전 지도사
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          timeout: 5000           # 이메일 전송 타임아웃 시간
          starttls:
            enable: true          # TLS를 통해 안전한 통신 사용 여부

jwt:
  secret: vosdfay6ghfasdfasldfjasldfmxcfvojalksnfskdsdgfn

## mybatis
#mybatis:
##  mapper-locations: classpath:mappers/**/*.xml
#  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: net.gidosa.full.webapp.mappers
##  configuration:
##    map-underscore-to-camel-case: true

# log
#logging:
#  level:
#   root: INFO

# 파일 업로드 경로 설정
file:
  upload-dir: /Users/pktjesus/uploads/gidosa/webapp
  # upload:
  #   path: C:\\uploads