spring:
  profiles:
    active: local
    group:
      local:
        - common
      dev:
        - common
      prod:
        - common
        -

  # mail:
  #   host: 
  #   port: 
  #   username: 
  #   password: 
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true




