# 서버포트
server:
  port: 9096
  #  forward-headers-strategy: framework
  error:
    whitelabel:
      enabled: true

# spring-web-jpa
spring:
  application:
    name: gidosa-webapp-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

  thymeleaf:          # 타임리프
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*
    enabled: true
  #    check-template-location: true

  mvc:
    #    static-path-pattern: /**
    view:         # 제이에스피
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
#    context-path: /api

  jpa:
    hibernate:
      ddl-auto: none
    #    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
    #        format_sql: true
    jwt:
      secret:

# mybatis
mybatis:
  #  mapper-locations: classpath:mappers/**/*.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: net.gidosa.webapp.mappers
#  configuration:
#    map-underscore-to-camel-case: true

# log